# ---------------------------------------------------------------------------
# Client VPN endpoint (created once; subnet association is done ON DEMAND by
# the toggle Lambda, so there is $0 association cost while idle).
# Auth: IAM Identity Center federation (SAML). Transport: server cert (public
# DNS-validated ACM cert — no local private key).
# ---------------------------------------------------------------------------

# Server certificate: use the provided ARN, or (default) auto-generate a
# self-signed cert via the tls provider and import it to ACM. The private key is
# generated by Terraform and lives ONLY in state (never on disk, never in git).
# A self-signed server cert is standard/sufficient for Client VPN — clients trust
# it via the CA embedded in their downloaded config.
locals {
  create_server_cert        = var.server_certificate_arn == ""
  effective_server_cert_arn = var.server_certificate_arn != "" ? var.server_certificate_arn : aws_acm_certificate.server[0].arn
  server_cert_cn            = var.server_cert_domain != "" ? var.server_cert_domain : "server.${var.project_name}.vpn.internal"
}

resource "tls_private_key" "server" {
  count     = local.create_server_cert ? 1 : 0
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "server" {
  count           = local.create_server_cert ? 1 : 0
  private_key_pem = tls_private_key.server[0].private_key_pem

  subject {
    common_name = local.server_cert_cn
  }

  validity_period_hours = 87600 # 10 years
  early_renewal_hours   = 720
  allowed_uses          = ["digital_signature", "key_encipherment", "server_auth"]
  dns_names             = [local.server_cert_cn]
}

resource "aws_acm_certificate" "server" {
  count            = local.create_server_cert ? 1 : 0
  private_key      = tls_private_key.server[0].private_key_pem
  certificate_body = tls_self_signed_cert.server[0].cert_pem
}

# Security group applied to the Client VPN ENIs when associated.
resource "aws_security_group" "vpn" {
  name        = "${local.name}-cvpn-sg"
  description = "Client VPN endpoint SG - allow outbound so client traffic can egress via NAT"
  vpc_id      = var.vpc_id

  egress {
    description      = "All egress (routed to internet via sharer NAT)"
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }

  tags = { Name = "${local.name}-cvpn-sg" }
}

resource "aws_cloudwatch_log_group" "vpn" {
  name              = "/aws/clientvpn/${local.name}"
  retention_in_days = 14
}

resource "aws_cloudwatch_log_stream" "vpn" {
  name           = "connection-log"
  log_group_name = aws_cloudwatch_log_group.vpn.name
}

resource "aws_ec2_client_vpn_endpoint" "this" {
  description            = "${local.name} ephemeral Client VPN (IDC SAML, on-demand association)"
  server_certificate_arn = local.effective_server_cert_arn
  client_cidr_block      = var.client_cidr_block

  # Full-tunnel: send all client traffic through the VPN so egress uses the NAT IP.
  split_tunnel = false

  # DNS: the shared VPC has DNS64 enabled, which makes the VPC resolver return
  # synthetic NAT64 IPv6 (64:ff9b::/96) addresses. This tunnel is IPv4-only, so
  # those are unroutable and clients hang. Use public IPv4 resolvers instead;
  # with split_tunnel=false, DNS still egresses via the NAT. (Trade-off: private
  # VPC hostnames won't resolve — fine for the fixed-egress-IP use case.)
  dns_servers = var.dns_servers

  transport_protocol = "udp"
  vpn_port           = 443

  # Self-service portal is available with federated (SAML) auth.
  self_service_portal = var.auth_mode == "federated" ? "enabled" : "disabled"

  authentication_options {
    type                           = var.auth_mode == "federated" ? "federated-authentication" : "certificate-authentication"
    saml_provider_arn              = var.auth_mode == "federated" ? local.effective_saml_arn : null
    self_service_saml_provider_arn = var.auth_mode == "federated" && local.effective_portal_arn != "" ? local.effective_portal_arn : null
    root_certificate_chain_arn     = var.auth_mode == "certificate" ? var.root_certificate_chain_arn : null
  }

  connection_log_options {
    enabled               = true
    cloudwatch_log_group  = aws_cloudwatch_log_group.vpn.name
    cloudwatch_log_stream = aws_cloudwatch_log_stream.vpn.name
  }

  security_group_ids = [aws_security_group.vpn.id]
  vpc_id             = var.vpc_id

  tags = { Name = "${local.name}-cvpn" }

  # SAML provider / client CA + server cert must exist before creating the endpoint.
  lifecycle {
    precondition {
      condition     = local.effective_server_cert_arn != ""
      error_message = "Server certificate could not be resolved."
    }
    precondition {
      condition     = var.auth_mode != "federated" || local.effective_saml_arn != ""
      error_message = "auth_mode = federated requires an IDC SAML provider: set client_saml_metadata_file or saml_provider_arn."
    }
    precondition {
      condition     = var.auth_mode != "certificate" || var.root_certificate_chain_arn != ""
      error_message = "auth_mode = certificate requires root_certificate_chain_arn (client CA in ACM)."
    }
  }
}

# Authorization rule: allow all federated users to reach the target network(s).
# Authorization rules are cheap/instant and can stay in place; only the SUBNET
# ASSOCIATION (the billed part) is toggled on demand by the Lambda.
resource "aws_ec2_client_vpn_authorization_rule" "all" {
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.this.id
  target_network_cidr    = var.vpn_access_cidr
  authorize_all_groups   = true
}
